### ISSUE TITLE
remove abbreviations and replace their usage

### ISSUE THREAD

**Issue by Kokan** [Kokan/toowtrsywen#26]
The document has hard abbreviations that makes it harder to read, inline those: 

- ATI: (daily) arrival time of EMP to the workplace
- WTRS: Working time recording system, the software to be developed and delivered under this software development project
- EMP: employee
- EXT: extraordinary events (etc. human neglect, inattention, system error, power outage, blackout)
- OTS: outside the system (etc. in spoken words, in e-mail, on the phone, on telegraph, courier)
- DTI: departure time of EMP from the workplace
- LDE: leader

**Comment by tarczi** [comment]
Egyúttal kivettem a feature-öknél a fejezetszámozást, mert szerintem az is jelentősen nehezítette az áttekinthetőséget (illetve redundáns is volt a feature számozások mellett). A tartalomjegyzékben sem lesz rá szükség, hiszen ott hivatkozhatunk majd a feature számozásokra, az alpontoknak meg nem is kell ott lenniük. A definíciók listáját is bővítettem kicsit.
