### ISSUE TITLE
2.1 Product perspective

### ISSUE THREAD

**Issue by tarczi** [Kokan/toowtrsywen#33]
Context diagram made with draw.io, should be possible to edit the .png there if you can extract it from the doc somehow :D

**Comment by Kokan** [comment]
Next time please try saving it also to the shared google drive, so others later could easily modify it. (well the browser displays the image, so you should have the png somewhere stored, but I am not sure if draw.io really could work with png).

**Comment by tarczi** [comment]
Tried it and it works for some reason :D, you can modify everything as you wish. The site stores some kind of data embedded in the .png when you export it. I’ll upload the file to the directory later.

**Comment by Kokan** [comment]
Sure with the not stripped png :) Thanks.
