### ISSUE TITLE
provide a five-star user experience for the reader of the requirement documentation

### ISSUE THREAD

**Issue by stadtrundfahrt** [Kokan/toowtrsywen#38]
Attila Kovacs, teacher at lecture: a requirement documentation of good quality means using cross-references (clickable in-pdf links, e.g. "Related requirement(s): ...")

Someone to investigate Google Doc's built-in possibilities (in the Add-ons section maybe?).

Converting each (major) doc version into some word processor (MS Word), and re-create the links again and agian is beleived to work at a high cost of maintenance.

And, of course, there's LaTeX. It can work.

**Comment by tarczi** [comment]
I mean, I wouldn't call it a five-star experience, but I made a whole bunch of links to relating sections throughout the doc using the built-in hyperlink function. Hopefully they will function on the teacher's end as well.
