### ISSUE TITLE
Structuring requirement sentences.

### ISSUE THREAD

**Issue by stadtrundfahrt** [Kokan/toowtrsywen#55]
Two possible templates for structuring sentences.

Template 1:
- when / condition
- (the system)
- SHALL (=a must) / SHOULD / WILL (=nice to have) (order by priority descending)
-:
-- (process)
-- provide (whom) with the ability to (process)
-- be able to
- (object)
- details of the object

Template 2 (~agile)
- given (precondition)
-:
a)
-- when
-- possible (event) happens
-- initiated by (actor)
b)
-- when unexpectedly
-- unwanted (event) happens
- then
- some response

**Comment by Kokan** [comment]
I vote here for the first option.
