### ISSUE TITLE
Registration Page for new members

### ISSUE THREAD

**Issue by bekezoltan00** [Kokan/toowtrsywen#59]
.

**Comment by bekezoltan00** [comment]
Already on branch: "RegistrationPage"

**Comment by amatyi96** [comment]
Erre biztos van szükség? Szerintem elég, ha az admin hozzá tud adni új felhasználót.

**Comment by bekezoltan00** [comment]
Igen, igazad lehet... viszont az Admin-nak is kell egy felület, ahol hozzáadhatja az új felhasználókat! ;)

**Comment by amatyi96** [comment]
Django van ilyen beépített felülelt!

**Comment by stadtrundfahrt** [comment]
(Isn't our system supposed to be integrated into an ecosystem of an enterprise?
I thought, e.g. we are provided APIs for the HR system to check in from time to time whether a new employee created in the "HR" system etc. (I didn't read now the ReqDoc, though.)
Of course, the thumb rule is: choose which is easier to develop... :-D)

**Comment by Kokan** [comment]
@stadtrundfahrt Yes that is the requirement. But according to the teacher we are not required to implement everything as it is written, we could do development in iteration and deviate from the plan. 
While it does not seems like a logical iteration (and maybe it is not) as we do not get that API implemented, in that case we should implement both of them (one simulator for that API), that might be more work. So I wanted to keep that as an open question for the implementer as written in the https://github.com/Kokan/toowtrsywen/issues/47.

The current implementation is done via using database, that should be fine for now.

@bekezoltan00 if you agree please close the issue.
